// Command neon generates the arm64 NEON assembly for the hash_neon package.
//
// The kernels process four chunks (or parents) per pass in the lanes of
// 128-bit vectors, following the reference NEON implementation in the
// upstream BLAKE3 repository. State is kept transposed: vector register i
// holds word i of the compression state across the four lanes.
package main

import (
	"bufio"
	"os"
)

func main() {
	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()

	a := &asm{w: w}
	a.line("// Code generated by command: go run ./neon. DO NOT EDIT.")
	a.line("")
	a.line("#include \"textflag.h\"")
	a.line("")
	emitData(a)
	emitHashF(a)
	emitHashP(a)
}
