package main

import (
	"bufio"
	"os"
)

func main() {
	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()

	a := &asm{w: w}
	a.line("// Code generated by command: go run ./neon. DO NOT EDIT.")
	a.line("")
	a.line("#include \"textflag.h\"")
	a.line("")
	emitData(a)
	emitHashF(a)
	emitHashP(a)
}
