package main

import (
	"bufio"
	"fmt"
	"os"
)

func main() {
	w := bufio.NewWriter(os.Stdout)

	a := &asm{w: w}
	a.line("// Code generated by command: go run ./sve2. DO NOT EDIT.")
	a.line("")
	a.line("#include \"textflag.h\"")
	a.line("")
	emitData(a)
	emitHashF(a)
	emitHashP(a)

	if a.err == nil {
		a.err = w.Flush()
	}
	if a.err != nil {
		fmt.Fprintln(os.Stderr, a.err)
		os.Exit(1)
	}
}
